CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE "CatalogBrand" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Brand" character varying(100) NOT NULL
);

CREATE TABLE "CatalogType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Type" character varying(100) NOT NULL
);

CREATE TABLE "Catalog" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" character varying(50) NOT NULL,
    "Description" text,
    "Price" numeric NOT NULL,
    "PictureFileName" text,
    "CatalogTypeId" integer NOT NULL,
    "CatalogBrandId" integer NOT NULL,
    "AvailableStock" integer NOT NULL,
    "RestockThreshold" integer NOT NULL,
    "MaxStockThreshold" integer NOT NULL,
    "Embedding" vector(384),
    "OnReorder" boolean NOT NULL,
    CONSTRAINT "FK_Catalog_CatalogBrand_CatalogBrandId"
        FOREIGN KEY ("CatalogBrandId") REFERENCES "CatalogBrand" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Catalog_CatalogType_CatalogTypeId"
        FOREIGN KEY ("CatalogTypeId") REFERENCES "CatalogType" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Catalog_CatalogBrandId" ON "Catalog" ("CatalogBrandId");
CREATE INDEX "IX_Catalog_CatalogTypeId" ON "Catalog" ("CatalogTypeId");
CREATE INDEX "IX_Catalog_Name" ON "Catalog" ("Name");

INSERT INTO "CatalogBrand" ("Id", "Brand") VALUES (1, '.NET');
INSERT INTO "CatalogType" ("Id", "Type") VALUES (1, 'Mug');
INSERT INTO "Catalog" (
    "Id", "Name", "Description", "Price", "PictureFileName",
    "CatalogTypeId", "CatalogBrandId",
    "AvailableStock", "RestockThreshold", "MaxStockThreshold", "OnReorder"
) VALUES (
    1, 'Test Mug', 'A test mug', 8.50, '1.webp',
    1, 1,
    100, 10, 200, false
);
